ASPECTS_CLICKHOUSE_CMS_PASSWORD: CTr93c8cLJGg6ZT6gAl1dhTy
ASPECTS_CLICKHOUSE_CMS_USER: ch_cms
ASPECTS_CLICKHOUSE_LRS_PASSWORD: H4PhxiANv23tmOcL3nAeQQTX
ASPECTS_CLICKHOUSE_LRS_USER: ch_lrs
ASPECTS_CLICKHOUSE_REPORT_PASSWORD: 6lVwUJ4p6SLosW86u0tRKWn8
ASPECTS_CLICKHOUSE_REPORT_USER: ch_report
ASPECTS_CLICKHOUSE_VECTOR_PASSWORD: 1lReLfYAbyrsdwp7AcQF3paw
ASPECTS_CLICKHOUSE_VECTOR_USER: ch_vector
CLICKHOUSE_ADMIN_PASSWORD: DHkFoZQ2lTH7fF3N1hUOQplI
CLICKHOUSE_ADMIN_USER: ch_admin
CLICKHOUSE_SECURE_CONNECTION: false
CMS_HOST: studio.local.overhang.io
CMS_OAUTH2_SECRET: V8553RMCO27CBJEx3X4xTh9a
CONTACT_EMAIL: oscm@axim.org
ENABLE_HTTPS: false
ID: QHbF6pRUqoRIPS6HAULDtfiJ
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpQIBAAKCAQEAzikDcXeaAH4ovS/bpIOL0GobhcNoBfKsRok1dafTHP0m0CNR

  DzJFiZIbYSp2N//de2/pIcjuD9dWHZhsytc+WIZq9jt24VchjI5UAzLcAURKh64U

  qHUfaMsBGnmCMZhq0+eN3SXCJijcqMRAnrTztUrtGcZUrgNh5IGwLMxm5Tq3khrA

  n3vz+gF8xWRs1EAUwl991gRXQnurlPcQHlhm0uSJ32CwI4kLOcmkGSQYVVMAXPBG

  UtSxEUKyDt1LDUPmOnC+Y+j36nYinDs16EUBUeLiGqXZ1ZaKIqxL7/QAQ4S96PfU

  IdNoNePX9UKW40uAi/HpBSSUmJ5jmRDNLiPDowIDAQABAoIBAFrXe6rt9rAs5yqm

  AfS1+k+10bbZaeblDcBvCV10u/PUINwqE7fMgROji+j+2uTGHAQeRe4bKbtVOZ8E

  4TtoKRK8+DjT7whQanoS5TYbnRH505WBwZyRL2vvt+bAj/vmm3wQVlSSJMDH1KOR

  BqBoP9Ms1tk6qWmcF/CmrMiwsM5ki52g1VaVCSN/FkCBZ+YQ636+AE3fsXTfvNWa

  JgGRqmyCxp1rvVz8J5rqpsXPGorvybE5U1NDnUpQaKKrXCax86te8ievJiDWQ+aN

  8yV0WhmzASrciCMlu95roYWHqiP2UHOcIOdtiaHZ7BoVBjgr7JXRqXriD6NZ4h23

  /oby1FECgYEAzxMg5fdc+6zyvE8szxOyFFyTNxKcQMQThC9rBd3BHufqh4qpdtWs

  N6DSz3pVndUpsHDLssT26eyCUIr4p80YM2hYyX5dq1BmufyP/cWRBaL9xYCGbpeF

  NWlKB2E9nf65CHBuYnJieoLu/02QpzIY6EIMrBn73kn/iGkueZo3mkcCgYEA/t6S

  JOoE6N8T8ugUr1zMwEWoiqtddLjwn1gnAGowGAKwOcCdqxZa4UH2RBVQOMarcWw2

  sPr3iMnjnogPRT866Ey1B12QJB/4NizetYseOUssSf3NVsj/zhC1FYKXrch4e1Fi

  apRhsHK5t81BIwtw2ubRwlkR46pAjmu0DLQgHcUCgYEAscGX4hD/7sO980x8CJ69

  paD6drIxE5+9qSETXAvKNf+bYhLz+iDeHzqc/KHlUQGlMeMB2UofMxtlmkJRxanX

  dnnCjeU9/0ubg1h9OrkYDqCl+56ix9il7v2dIMymmjQJHmd1Omk6hDRVeS9aV0w3

  +ViJjEsZ3O3kv3KbBKQPyw0CgYEA8+wLrmySGlU1gGqBMXv9MZ75OQ3cuZMuJzJ0

  0T7PnIsmIX+o5k7U13ULvgkv58ar2jeY+DSYpz+hKt5Izxs+w4h2UQBIrWozYZX7

  53+ng2ngj0fqN77So2L2DAoaJGYSeONg72PnQrnp6HD2gBW5AqeZ5QjdyCfu9N87

  SFUzz4kCgYEAuR0jhcMdh9KA2VrYaqMa8c4HBTjBkb9trgNMb55vfKB/O0q6NfBg

  KcT1MM56FmhPLj3P1aDKPliczaOxsbRh4oRQYTSUSOCdvhXe9ZilrnFHelVmIw07

  i8A6TC850sHwR1j3p1wfyAaHX7eCPMP4EglRzHEjSRfFw1x5CwnejPk=

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.overhang.io
MYSQL_ROOT_PASSWORD: 6KFFc2L9
OPENEDX_MYSQL_PASSWORD: 93pugaBr
OPENEDX_SECRET_KEY: 6BxYaHmIkV8R3tFm96UcLBMG
PLATFORM_NAME: Aspects Local CI Test
PLUGINS:
- aspects
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
RALPH_ADMIN_HASHED_PASSWORD: $2b$12$tUVfJTDDwFSe4wOh5ysJd.LGa6SNyaFvzj7FnC6Oc9REVoeCWHMfu
RALPH_ADMIN_PASSWORD: wlnktlsthqiprtsvanzrcynhnbvoxirmvzwv
RALPH_ADMIN_USERNAME: ralph
RALPH_LMS_HASHED_PASSWORD: $2b$12$tIHqFKghkExV/pqzN.pDmesz60PEWB4Cy1Q.Jg.lwOVvoYMHCDVu.
RALPH_LMS_PASSWORD: jpjgcgrlnnarlsgjhnkmguhdogqhslwwedmg
RALPH_LMS_USERNAME: lms
SUPERSET_ADMIN_PASSWORD: rGYfsLzCPcFBRL5grttE5JxR
SUPERSET_ADMIN_USERNAME: frzy1EHeGXlY
SUPERSET_DB_PASSWORD: A7CG3FSpABCgWPWtnHiJFe7Y
SUPERSET_OAUTH2_CLIENT_ID: vZHFGoAE9VPjMOVn
SUPERSET_OAUTH2_CLIENT_ID_DEV: OlR3BXJBNx9C21N7
SUPERSET_OAUTH2_CLIENT_SECRET: StkPwE5GzPuyH4Rp
SUPERSET_ROW_LEVEL_SECURITY_XAPI_GROUP_KEY: xapi_course_id
SUPERSET_SECRET_KEY: WlgA6QSQKCUNGD9PAaji0JHY
SUPERSET_XAPI_DASHBOARD_SLUG: openedx-xapi
ASPECTS_VERSION: 2.5.0
DOCKER_IMAGE_OPENEDX: edunext/openedx-aspects:{{ASPECTS_VERSION}}
DOCKER_IMAGE_OPENEDX_DEV: edunext/openedx-aspects-dev:{{ASPECTS_VERSION}}
ASPECTS_ENABLE_EVENT_BUS_CONSUMER: true
ASPECTS_ENABLE_EVENT_BUS_PRODUCER: true
# Limit languages to 2 to speed up CI times
SUPERSET_DASHBOARD_LOCALES:
- en
- fr_CA
RUN_ASPECTS_DOCS: true
ASPECTS_ENABLE_STUDIO_IN_CONTEXT_METRICS: true
