- _file_name: Actor_IDs_over_time_47.yaml
  cache_timeout: null
  dataset_uuid: 2a2498dc-03ce-41a0-b798-d84f808f7da6
  params:
    adhoc_filters: []
    color_picker:
      a: 1
      b: 135
      g: 122
      r: 0
    datasource: 4__table
    extra_form_data: {}
    granularity_sqla: emission_time
    header_font_size: 0.4
    metric:
      aggregate: COUNT_DISTINCT
      column:
        advanced_data_type: null
        certification_details: null
        certified_by: null
        column_name: actor_id
        description: null
        expression: null
        filterable: true
        groupby: true
        id: 35
        is_certified: false
        is_dttm: false
        python_date_format: null
        type: String
        type_generic: 1
        verbose_name: null
        warning_markdown: null
      expressionType: SIMPLE
      hasCustomLabel: false
      isNew: false
      label: COUNT_DISTINCT(actor_id)
      optionName: metric_oeitb1mn4se_b9rg6pdr51g
      sqlExpression: null
    rolling_type: None
    show_trend_line: true
    start_y_axis_at_zero: true
    subheader_font_size: 0.2
    time_format: smart_date
    time_grain_sqla: P1D
    time_range: No filter
    viz_type: big_number
    y_axis_format: SMART_NUMBER
  slice_name: Actor IDs over time
  uuid: 6a8ded91-f9a6-45c2-9f9f-f85dc1ff7ed6
  version: 1.0.0
  viz_type: big_number
