_file_name: Course_Grade_Distribution.yaml
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: d777bd95-2110-46db-a1c4-8358be81a85a
description: The distribution of grades for a course, out of 100%. Grades are grouped
  in ranges of 10%.
params:
  adhoc_filters: []
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  dashboards:
  - 23
  datasource: 16__table
  extra_form_data: {}
  granularity_sqla: emission_time
  groupby:
  - grade_bucket
  metrics:
  - count
  order_bars: true
  order_desc: true
  rich_tooltip: true
  row_limit: 10000
  show_legend: false
  slice_id: 352
  time_range: 'DATEADD(DATETIME("now"), -1, month) : DATEADD(DATETIME("now"), 1, day)'
  viz_type: dist_bar
  x_axis_label: Course Grade (out of 100%)
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_label: Number Of Students
query_context: null
slice_name: Course Grade Distribution
uuid: f9adbc85-1f50-4c04-ace3-31ba7390de5e
version: 1.0.0
viz_type: dist_bar
