_file_name: Course_Enrollments_Over_Time.yaml
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 352311fe-12f0-470c-8b8c-d4f6a3936b3d
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: registered
    expressionType: SIMPLE
    filterOptionName: filter_0boo7wmml3y9_u9cjkku59hh
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: enrollment_status
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: enrollment_status_date
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards:
  - 14
  datasource: 1__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby:
  - enrollment_status
  legendOrientation: top
  legendType: scroll
  markerSize: 6
  metrics:
  - aggregate: COUNT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: enrollment_status
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 10
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: String
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT(enrollment_status)
    optionName: metric_iapetcrge8_4fkcsr2b3nj
    sqlExpression: null
  only_total: true
  opacity: 0.2
  order_desc: true
  rich_tooltip: true
  row_limit: 10000
  seriesType: line
  show_empty_columns: true
  show_legend: true
  slice_id: 272
  sort_series_type: sum
  time_grain_sqla: P1D
  tooltipTimeFormat: smart_date
  truncate_metric: true
  viz_type: echarts_timeseries_line
  x_axis: enrollment_status_date
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title: Registrations
  y_axis_title_margin: 15
  y_axis_title_position: Left
query_context: null
slice_name: Course Enrollments Over Time
uuid: bf4f4671-c276-4185-9b9a-b10864efea6c
version: 1.0.0
viz_type: echarts_timeseries_line
