_file_name: Courses_Per_Organization.yaml
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 46183302-6fa6-41a3-b6a7-79ff6c1c8402
description: null
params:
  adhoc_filters: []
  color_scheme: supersetColors
  datasource: 8__table
  date_format: smart_date
  extra_form_data: {}
  groupby:
  - org
  innerRadius: 30
  label_type: key
  labels_outside: true
  legendOrientation: top
  legendType: scroll
  metric:
    aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: course_key
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 63
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: String
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT_DISTINCT(course_key)
    optionName: metric_fzi7lg939n_f99m825il4q
    sqlExpression: null
  number_format: SMART_NUMBER
  outerRadius: 70
  row_limit: 100
  show_labels: true
  show_labels_threshold: 5
  show_legend: true
  slice_id: 453
  sort_by_metric: true
  time_range: No filter
  viz_type: pie
query_context: null
slice_name: Courses Per Organization
uuid: 7901d6ae-dea8-4d2c-9232-35c22571cfb7
version: 1.0.0
viz_type: pie
