_file_name: Enrollments_By_Enrollment_Mode.yaml
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: a234545d-08ff-480d-8361-961c3d15f14f
description: The current count of active enrollments by their most recent enrollment
  type, so if a learner upgraded from Audit to Verified they will only be counted
  once as Verified. Learners who have un-enrolled in the course are not counted.
params:
  adhoc_filters:
  - clause: WHERE
    comparator: registered
    expressionType: SIMPLE
    filterOptionName: filter_itrvc9c0jxb_g4qd4b18na4
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: enrollment_status
  color_scheme: supersetColors
  dashboards:
  - 23
  datasource: 11__table
  date_format: smart_date
  extra_form_data: {}
  granularity_sqla: emission_time
  groupby:
  - enrollment_mode
  innerRadius: 30
  label_type: key
  labels_outside: true
  legendOrientation: top
  legendType: scroll
  metric: count
  number_format: SMART_NUMBER
  outerRadius: 70
  row_limit: 100
  show_labels: true
  show_labels_threshold: 5
  show_legend: true
  slice_id: 40
  sort_by_metric: true
  time_range: 'DATEADD(DATETIME("now"), -1, month) : DATEADD(DATETIME("now"), 1, day)'
  viz_type: pie
query_context: null
slice_name: Enrollments By Enrollment Mode
uuid: 05ed7102-5464-4e2f-86ae-31700b787cc3
version: 1.0.0
viz_type: pie
