- _file_name: Enrollment_events_per_day_16.yaml
  cache_timeout: null
  dataset_uuid: a234545d-08ff-480d-8361-961c3d15f14f
  params:
    adhoc_filters: []
    annotation_layers: []
    color_scheme: supersetColors
    comparison_type: values
    datasource: 14__table
    extra_form_data: {}
    forecastInterval: 0.8
    forecastPeriods: 10
    granularity_sqla: emission_time
    groupby:
    - enrollment_status
    legendOrientation: top
    legendType: scroll
    metrics:
    - count
    only_total: true
    order_desc: true
    orientation: vertical
    rich_tooltip: true
    row_limit: 10000
    show_legend: true
    stack: true
    time_grain_sqla: P1D
    time_range: No filter
    tooltipTimeFormat: smart_date
    truncate_metric: true
    viz_type: echarts_timeseries_bar
    xAxisLabelRotation: 45
    x_axis_time_format: '%Y-%m-%d'
    x_axis_title_margin: 15
    y_axis_bounds:
    - null
    - null
    y_axis_format: SMART_NUMBER
    y_axis_title_margin: 15
    y_axis_title_position: Left
  slice_name: Enrollment events per day
  uuid: bb1147cc-b7bc-44b7-b06a-79b0db6626aa
  version: 1.0.0
  viz_type: echarts_timeseries_bar
