_file_name: monitoring.superset_top_users_by_action_count_365.yaml
slice_name: User Actions
viz_type: table
description: Chart showing the number of Superset actions taken by each user over the selected time period.
params:
  adhoc_filters: []
  all_columns: []
  color_pn: false
  conditional_formatting: []
  datasource: 473__table
  extra_form_data: {}
  granularity_sqla: action_date
  groupby:
  - user_name
  include_search: true
  include_time: false
  metrics:
  - aggregate: SUM
    column:
      certification_details: null
      certified_by: null
      column_name: action_count
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 47205
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(action_count)
    optionName: metric_kaadi7b6j0h_jvze06hjzln
    sqlExpression: null
  order_by_cols: []
  order_desc: true
  page_length: 10
  percent_metrics: []
  query_mode: aggregate
  row_limit: 50
  server_page_length: 10
  server_pagination: false
  show_cell_bars: false
  slice_id: 365
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: Last quarter
  time_range_endpoints:
  - inclusive
  - exclusive
  timeseries_limit_metric:
    aggregate: SUM
    column:
      certification_details: null
      certified_by: null
      column_name: action_count
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 47205
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(action_count)
    optionName: metric_xwajzb7l7en_xp4sy2czess
    sqlExpression: null
  url_params: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 8059fd82-efae-47a1-9c23-0b74f2707aa5
version: 1.0.0
dataset_uuid: c33517b3-daa5-4fac-b7f2-ae012b999d12
