- _file_name: Organizations_42.yaml
  cache_timeout: null
  dataset_uuid: 2a2498dc-03ce-41a0-b798-d84f808f7da6
  params:
    adhoc_filters: []
    datasource: 4__table
    extra_form_data: {}
    granularity_sqla: emission_time
    header_font_size: 0.4
    metric:
      aggregate: COUNT_DISTINCT
      column:
        advanced_data_type: null
        certification_details: null
        certified_by: null
        column_name: org
        description: null
        expression: null
        filterable: true
        groupby: true
        id: 39
        is_certified: false
        is_dttm: false
        python_date_format: null
        type: String
        type_generic: 1
        verbose_name: null
        warning_markdown: null
      expressionType: SIMPLE
      hasCustomLabel: false
      isNew: false
      label: COUNT_DISTINCT(org)
      optionName: metric_3n2fzhdsmw5_rg9hrwirg3f
      sqlExpression: null
    subheader_font_size: 0.15
    time_format: smart_date
    time_grain_sqla: P1D
    time_range: No filter
    viz_type: big_number_total
    y_axis_format: SMART_NUMBER
  slice_name: Organizations
  uuid: e66b1cdb-6974-4fa2-a769-4908665118f6
  version: 1.0.0
  viz_type: big_number_total
