- _file_name: Problem_submission_counts_38.yaml
  cache_timeout: null
  dataset_uuid: 9362354c-1541-43c2-b769-da9818236298
  params:
    adhoc_filters: []
    bar_stacked: true
    bottom_margin: auto
    color_scheme: supersetColors
    columns:
      - success
    datasource: 43__table
    extra_form_data: {}
    groupby:
      - problem_name
    metrics:
      - aggregate: COUNT_DISTINCT
        column:
          advanced_data_type: null
          certification_details: null
          certified_by: null
          column_name: actor_id
          description: null
          expression: null
          filterable: true
          groupby: true
          id: 301
          is_certified: false
          is_dttm: false
          python_date_format: null
          type: String
          type_generic: 1
          verbose_name: null
          warning_markdown: null
        expressionType: SIMPLE
        hasCustomLabel: true
        isNew: false
        label: Learners
        optionName: metric_g889221mh0r_lf203igqxgg
        sqlExpression: null
    order_desc: true
    rich_tooltip: true
    row_limit: 10000
    show_legend: true
    slice_id: "38"
    time_range: No filter
    viz_type: dist_bar
    x_ticks_layout: auto
    y_axis_bounds:
      - null
      - null
    y_axis_format: SMART_NUMBER
  slice_name: Problem submission counts
  uuid: 3dc6a642-a71d-4c8c-ab98-14f54852b40f
  version: 1.0.0
  viz_type: dist_bar
