_file_name: Responses_Per_Problem.yaml
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 981f30d9-b2f0-4a0b-9e95-0ee0e06db806
description: The number of students who have responded to a question, and whether
  they have ever answered correctly. Students can answer some questions multiple times,
  but this chart counts each student only once per question.
params:
  adhoc_filters: []
  bar_stacked: true
  bottom_margin: auto
  color_scheme: supersetColors
  columns:
  - success
  dashboards:
  - 23
  datasource: 2__table
  extra_form_data: {}
  groupby:
  - problem_name_with_location
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: actor_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 301
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: String
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Learners
    optionName: metric_g889221mh0r_lf203igqxgg
    sqlExpression: null
  order_bars: false
  order_desc: true
  rich_tooltip: true
  row_limit: 10000
  show_controls: false
  show_legend: false
  slice_id: 262
  time_range: 'DATEADD(DATETIME("now"), -1, month) : DATEADD(DATETIME("now"), 1, day)'
  viz_type: dist_bar
  x_axis_label: Question Title
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_label: Number Of Students
query_context: null
slice_name: Responses Per Problem
uuid: a3e79162-4ace-4349-ab34-89aa60ae75ed
version: 1.0.0
viz_type: dist_bar
