_file_name: Watched_Video_Segments.yaml
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: c2c391b3-3403-4f05-bc0b-3de53bd366ec
description: This chart shows which parts of a video are most watched, and which are
  most re-watched. Each segment represents 5 seconds of the video.
params:
  adhoc_filters: []
  bar_stacked: true
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  dashboards:
  - 23
  datasource: 8__table
  extra_form_data: {}
  granularity_sqla: started_at
  groupby:
  - segment_start
  metrics:
  - unique_viewers
  - repeat_views
  order_bars: true
  order_desc: true
  rich_tooltip: true
  row_limit: 10000
  show_legend: true
  slice_id: 204
  time_range: 'DATEADD(DATETIME("now"), -1, month) : DATEADD(DATETIME("now"), 1, day)'
  viz_type: dist_bar
  x_axis_label: Seconds Of Video
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_label: Number Of Viewers / Views
query_context: null
slice_name: Watched Video Segments
uuid: 2985a9db-c338-4008-af52-2930b81ee2e5
version: 1.0.0
viz_type: dist_bar
