- _file_name: xAPI_events_38.yaml
  cache_timeout: null
  dataset_uuid: 2a2498dc-03ce-41a0-b798-d84f808f7da6
  params:
    adhoc_filters: []
    color_picker:
      a: 1
      b: 135
      g: 122
      r: 0
    datasource: 4__table
    extra_form_data: {}
    granularity_sqla: emission_time
    header_font_size: 0.4
    metric: count
    rolling_type: null
    show_trend_line: true
    slice_id: 38
    start_y_axis_at_zero: true
    subheader_font_size: 0.15
    time_format: smart_date
    time_grain_sqla: P1D
    time_range: No filter
    viz_type: big_number
    y_axis_format: SMART_NUMBER
  slice_name: xAPI events
  uuid: e6a30923-6382-413e-a1c7-2ac223fa5c5c
  version: 1.0.0
  viz_type: big_number
